# Generated by Django 3.1 on 2020-09-23 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0005_auto_20200923_0934'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Charge amount')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date and time usage fee was updated')),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.containertype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.currency')),
                ('surcharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_fees', to='booking.surcharge')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Charge amount')),
                ('conditions', models.CharField(choices=[('w/m', 'w/m'), ('per_weight', 'per weight'), ('per_no_of_packs', 'per no. of packs'), ('fixed', 'fixed')], default='fixed', max_length=20, verbose_name='Conditions')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date and time usage fee was updated')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.currency')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalSurcharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Additional surcharge title')),
                ('shipping_mode', models.ManyToManyField(related_name='additional_surcharges', to='handling.ShippingMode')),
            ],
        ),
        migrations.AddField(
            model_name='surcharge',
            name='container_types',
            field=models.ManyToManyField(related_name='surcharges', through='booking.UsageFee', to='handling.ContainerType'),
        ),
    ]
