# Generated by Django 3.1 on 2020-09-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200923_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='charge',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AdditionalSurcharge',
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
