# Generated by Django 3.1 on 2020-09-24 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200924_1359'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handling', '0005_auto_20200923_0934'),
        ('booking', '0004_auto_20200923_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transit_time', models.PositiveIntegerField(verbose_name='Transit time in days')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_rates', to='handling.carrier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_rates', to='core.company')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_freight_rates', to='handling.port')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_freight_rates', to='handling.port')),
                ('shipping_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_rates', to='handling.shippingmode')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Rate amount')),
                ('start_date', models.DateField(verbose_name='Rate start date')),
                ('expiration_date', models.DateField(verbose_name='Rate expiration date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date and time rate was updated')),
                ('container_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handling.containertype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.currency')),
                ('freight_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='booking.freightrate')),
                ('surcharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.surcharge')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
