# Generated by Django 3.1 on 2020-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200925_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surcharge',
            name='direction',
            field=models.CharField(choices=[('import', 'Import'), ('export', 'Export')], max_length=6, verbose_name='Surcharge direction, whether import or export'),
        ),
    ]
