# Generated by Django 3.1 on 2020-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20201002_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='additional_surcharges',
            new_name='additional_surcharge',
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Charge amount'),
        ),
        migrations.AlterField(
            model_name='usagefee',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Charge amount'),
        ),
    ]
