# Generated by Django 3.1 on 2020-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_freightrate_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Rate expiration date'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Rate amount'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Rate start date'),
        ),
    ]
