# Generated by Django 3.1 on 2020-11-04 14:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0013_auto_20201103_1421'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0013_auto_20201102_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Booing date from')),
                ('date_to', models.DateField(verbose_name='Booking date to')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Whether booking paid or not')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('freight_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.freightrate')),
            ],
        ),
        migrations.CreateModel(
            name='CargoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of items')),
                ('height', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Height')),
                ('length', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Width')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Weight')),
                ('dangerous', models.BooleanField(default=False, verbose_name='Dangerous freight')),
                ('frozen', models.CharField(choices=[('frozen', 'Frozen'), ('cold', 'Cold')], max_length=10, null=True, verbose_name='Frozen or chilled cargo')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_groups', to='booking.booking')),
                ('container_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handling.containertype')),
                ('packaging_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handling.packagingtype')),
            ],
        ),
    ]
