# Generated by Django 3.1 on 2020-11-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_shipper'),
        ('booking', '0014_booking_cargogroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.shipper'),
        ),
        migrations.AddField(
            model_name='cargogroup',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Cargo description'),
        ),
    ]
