# Generated by Django 3.1 on 2020-11-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20201105_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargogroup',
            name='frozen',
            field=models.CharField(choices=[('frozen', 'Chilled'), ('cold', 'Cold')], max_length=10, null=True, verbose_name='Frozen or chilled cargo'),
        ),
    ]
