# Generated by Django 3.1 on 2020-11-09 13:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20201108_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargogroup',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='cargogroup',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='cargogroup',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='cargogroup',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Width'),
        ),
    ]
