# Generated by Django 3.1 on 2020-11-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0017_auto_20201109_1319'),
        ('core', '0023_shipper'),
        ('booking', '0021_auto_20201109_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargogroup',
            name='length_measurement',
            field=models.CharField(choices=[('cm', 'cm'), ('m', 'm')], max_length=2, null=True, verbose_name='Length Measurement'),
        ),
        migrations.AddField(
            model_name='cargogroup',
            name='weight_measurement',
            field=models.CharField(choices=[('kg', 'kg'), ('t', 't')], max_length=2, null=True, verbose_name='Weight Measurement'),
        ),
        migrations.AlterField(
            model_name='cargogroup',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_groups', to='booking.booking'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Quote start date')),
                ('expiration_date', models.DateField(verbose_name='Quote expiration date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Quote is active or paused')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='core.company')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_quotes', to='handling.port')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_quotes', to='handling.port')),
                ('shipping_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='handling.shippingmode')),
            ],
        ),
        migrations.AddField(
            model_name='cargogroup',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_cargo_groups', to='booking.quote'),
        ),
    ]
