# Generated by Django 3.1 on 2020-11-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_auto_20201111_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='start_date',
            new_name='date_from',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='expiration_date',
            new_name='date_to',
        ),
    ]
