# Generated by Django 3.1 on 2020-11-12 12:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20201112_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargogroup',
            name='total_wm',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total w/m'),
        ),
        migrations.AddField(
            model_name='quote',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2020-2-2', verbose_name='Quote creation date'),
            preserve_default=False,
        ),
    ]
