# Generated by Django 3.1 on 2020-11-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20201112_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rejected', 'Rejected'), ('submitted', 'Submitted')], max_length=9, verbose_name='Quote - freight rate status')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Offer is viewed')),
                ('freight_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='booking.freightrate')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='booking.quote')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='freight_rates',
            field=models.ManyToManyField(related_name='quotes', through='booking.Status', to='booking.FreightRate'),
        ),
    ]
