# Generated by Django 3.1 on 2020-11-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_shipper'),
        ('booking', '0027_auto_20201116_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.company'),
        ),
    ]
