# Generated by Django 3.1 on 2020-11-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_status_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='freight_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='booking.freightrate'),
        ),
    ]
