# Generated by Django 3.1 on 2020-11-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20201117_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Booking confirmed or not'),
        ),
        migrations.AddField(
            model_name='freightrate',
            name='temporary',
            field=models.BooleanField(default=False, verbose_name='Temporary freight rate or not'),
        ),
        migrations.AddField(
            model_name='surcharge',
            name='temporary',
            field=models.BooleanField(default=False, verbose_name='Temporary surcharge or not'),
        ),
    ]
