# Generated by Django 3.1 on 2020-11-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_auto_20201117_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freightrate',
            name='transit_time',
            field=models.PositiveIntegerField(null=True, verbose_name='Transit time in days'),
        ),
    ]
