# Generated by Django 3.1 on 2020-11-18 19:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20201118_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='charges',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Charges calculations'),
        ),
    ]
