# Generated by Django 3.1 on 2020-11-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_auto_20201118_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='charges',
        ),
        migrations.AddField(
            model_name='status',
            name='charges',
            field=models.JSONField(null=True, verbose_name='Charges calculations'),
        ),
    ]
