# Generated by Django 3.1 on 2020-11-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_auto_20201119_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Booking confirmed'), ('pending', 'Waiting for confirmation'), ('received', 'Booking request received')], default='received', max_length=30, verbose_name='Booking confirmed or not'),
        ),
    ]
