# Generated by Django 3.1 on 2020-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_auto_20201120_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShipmentDetails',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='Is assigned to user'),
        ),
    ]
