# Generated by Django 3.1 on 2020-11-20 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_auto_20201120_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=20, verbose_name='Booking number')),
                ('booking_number_with_carrier', models.CharField(max_length=30, null=True, verbose_name='Booking number with carrier')),
                ('flight_number', models.CharField(max_length=30, null=True, verbose_name='Flight number')),
                ('vessel', models.CharField(max_length=30, null=True, verbose_name='Vessel number')),
                ('voyage', models.CharField(max_length=30, null=True, verbose_name='Voyage number')),
                ('container_number', models.CharField(max_length=30, null=True, verbose_name='Container number')),
                ('mawb', models.CharField(max_length=30, null=True, verbose_name='MAWB')),
                ('date_of_departure', models.DateTimeField(verbose_name='Estimated time of departure')),
                ('date_of_arrival', models.DateTimeField(verbose_name='Estimated time of arrival')),
                ('document_cut_off_date', models.DateTimeField(null=True, verbose_name='Document cut off date')),
                ('cargo_cut_off_date', models.DateTimeField(null=True, verbose_name='Cargo cut off date')),
                ('cargo_drop_off_location', models.CharField(max_length=100, null=True, verbose_name='Cargo drop off location')),
                ('cargo_drop_off_location_address', models.CharField(max_length=200, null=True, verbose_name='Cargo drop off location address')),
                ('empty_pick_up_location', models.CharField(max_length=100, null=True, verbose_name='Empty pick up location')),
                ('empty_pick_up_location_address', models.CharField(max_length=200, null=True, verbose_name='Empty pick up location address')),
                ('container_free_time', models.PositiveIntegerField(null=True, verbose_name='Container free time')),
                ('booking_notes', models.TextField(null=True, verbose_name='Booking notes')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_details', to='booking.booking')),
            ],
        ),
    ]
