# Generated by Django 3.1 on 2020-11-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_shipmentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdetails',
            name='cargo_pick_up_location',
            field=models.CharField(max_length=100, null=True, verbose_name='Cargo pick up location'),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='cargo_pick_up_location_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Cargo pick up location address'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Booking confirmed'), ('received', 'Booking request received')], default='received', max_length=30, verbose_name='Booking confirmed or not'),
        ),
    ]
