# Generated by Django 3.1 on 2020-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_auto_20201124_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Booking Confirmed'), ('accepted', 'Booking Request in Progress'), ('received', 'Booking Request Received')], default='received', max_length=30, verbose_name='Booking confirmed or not'),
        ),
    ]
