# Generated by Django 3.1 on 2020-11-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_auto_20201125_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charges',
            field=models.JSONField(null=True, verbose_name='Charges calculations'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=35, verbose_name='Transaction identifier')),
                ('status', models.CharField(choices=[('opened', 'Transaction opened'), ('finished', 'Transaction finished'), ('canceled', 'Transaction canceled'), ('expired', 'Transaction expired')], default='opened', max_length=20, verbose_name='Transaction status')),
                ('charge', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Transaction charge amount')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='booking.booking')),
            ],
        ),
    ]
