# Generated by Django 3.1 on 2020-11-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_auto_20201126_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Booking Confirmed'), ('accepted', 'Booking Request in Progress'), ('received', 'Booking Request Received'), ('pending', 'Booking Fee Pending')], default='pending', max_length=30, verbose_name='Booking confirmed or not'),
        ),
    ]
