# Generated by Django 3.1 on 2020-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_booking_aceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Quote is archived'),
        ),
    ]
