# Generated by Django 3.1 on 2020-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_quote_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Booking Confirmed'), ('accepted', 'Booking Request in Progress'), ('received', 'Booking Request Received'), ('pending', 'Booking Fee Pending'), ('rejected', 'Booking Request Rejected'), ('canceled_by_agent', 'Operation Canceled by Agent'), ('canceled_by_client', 'Operation Canceled by Client')], default='pending', max_length=30, verbose_name='Booking confirmed or not'),
        ),
    ]
