# Generated by Django 3.1 on 2020-12-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_booking_payment_due_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_freight_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_freight_rates', to='booking.booking'),
        ),
    ]
