# Generated by Django 3.1 on 2020-12-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_booking_original_freight_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='original_freight_rate',
        ),
        migrations.AddField(
            model_name='booking',
            name='original_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_bookings', to='booking.booking'),
        ),
    ]
