# Generated by Django 3.1 on 2020-12-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_auto_20201202_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetails',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_details', to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='booking.booking'),
        ),
    ]
