# Generated by Django 3.1 on 2020-12-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_auto_20201202_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='original_booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='booking.booking'),
        ),
    ]
