# Generated by Django 3.1 on 2020-12-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_auto_20201203_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('expired', 'Freight contract has expired.'), ('increased', 'Rate has been increased by Carrier.'), ('dates', 'We cannot meet the dates requested by the client or there was no space availability for this shipment.'), ('client_requested', 'Client requested the cancellation.'), ('other', 'Other')], max_length=20, null=True, verbose_name='Cancellation reason')),
                ('comment', models.TextField(null=True, verbose_name='Comment to cancellation reason')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='booking.booking')),
            ],
        ),
    ]
