# Generated by Django 3.1 on 2020-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_auto_20201209_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='surcharge',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Surcharge is archived'),
        ),
    ]
