# Generated by Django 3.1 on 2020-12-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0057_surcharge_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightrate',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Freight rate is archived'),
        ),
    ]
