# Generated by Django 3.1 on 2020-12-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_freightrate_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date the track object created')),
                ('data', models.JSONField(verbose_name='Json data from tracking api')),
            ],
        ),
    ]
