# Generated by Django 3.1 on 2020-12-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0060_auto_20201216_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='change_request_status',
            field=models.CharField(choices=[('change_requested', 'Booking Change Requested'), ('change_confirmed', 'Booking Change Confirmed')], max_length=30, null=True, verbose_name='Booking change request status'),
        ),
    ]
