# Generated by Django 3.1 on 2020-12-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0035_auto_20201223_1202'),
        ('booking', '0061_booking_change_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=6, verbose_name='Direction title')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='track',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment text'),
        ),
        migrations.AddField(
            model_name='track',
            name='route',
            field=models.JSONField(null=True, verbose_name='Json route data from tracking api'),
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Status title')),
                ('direction', models.ManyToManyField(to='booking.Direction')),
                ('shipping_mode', models.ManyToManyField(related_name='tracking_statuses', to='handling.ShippingMode')),
            ],
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.trackstatus'),
        ),
    ]
