# Generated by Django 3.1 on 2020-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0062_auto_20201223_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='manual',
            field=models.BooleanField(default=False, verbose_name='Manually created tracking event'),
        ),
    ]
