# Generated by Django 3.1 on 2020-12-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0063_track_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='Json data')),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='data',
            field=models.JSONField(null=True, verbose_name='Json data from tracking api'),
        ),
    ]
