# Generated by Django 3.1 on 2020-12-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_auto_20201228_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='automatic_tracking',
            field=models.BooleanField(default=False, verbose_name='Automatic status tracking'),
        ),
    ]
