# Generated by Django 3.1 on 2021-01-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_track_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-date_created',)},
        ),
    ]
