# Generated by Django 3.1 on 2021-01-12 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0068_auto_20210112_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date booking created'),
            preserve_default=False,
        ),
    ]
