# Generated by Django 3.1 on 2021-01-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0070_auto_20210114_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_accepted_by_agent',
            field=models.DateField(null=True, verbose_name='Date booking accepted by an agent'),
        ),
    ]
