# Generated by Django 3.1 on 2021-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0071_booking_date_accepted_by_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Booking Fee Pending'), ('received', 'Booking Request Received'), ('accepted', 'Booking Request in Progress'), ('confirmed', 'Booking Confirmed'), ('rejected', 'Booking Request Rejected'), ('canceled_by_agent', 'Operation Canceled by Agent'), ('canceled_by_client', 'Operation Canceled by Client'), ('canceled_by_system', 'Operation Canceled by the System'), ('completed', 'Operation Complete'), ('discarded', 'Booking Request Unpaid and Discarded')], default='pending', max_length=30, verbose_name='Booking confirmed or not'),
        ),
    ]
