# Generated by Django 3.1 on 2021-01-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0072_auto_20210114_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vessel_arrived',
            field=models.BooleanField(default=False, verbose_name='Vessel arrived status'),
        ),
    ]
