# Generated by Django 3.1 on 2021-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0073_booking_vessel_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdetails',
            name='actual_date_of_arrival',
            field=models.DateTimeField(null=True, verbose_name='Actual time of arrival'),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='actual_date_of_departure',
            field=models.DateTimeField(null=True, verbose_name='Actual time of departure'),
        ),
    ]
