# Generated by Django 3.1 on 2021-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0074_auto_20210120_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackstatus',
            name='must_update_actual_date_of_departure',
            field=models.BooleanField(default=False, verbose_name='Must update actual date of departure'),
        ),
    ]
