# Generated by Django 3.1 on 2021-01-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0075_trackstatus_must_update_actual_date_of_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackstatus',
            name='show_after_departure',
            field=models.BooleanField(default=False, verbose_name='Show status after actual date of departure set'),
        ),
    ]
