# Generated by Django 3.1 on 2021-02-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0077_auto_20210121_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackstatus',
            name='auto_add_on_shipment_details_change',
            field=models.BooleanField(default=False, verbose_name='Add the status after changing shipment details'),
        ),
    ]
