# Generated by Django 3.1 on 2021-03-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0078_trackstatus_auto_add_on_shipment_details_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentdetails',
            options={'verbose_name_plural': 'Shipment Details'},
        ),
        migrations.AlterModelOptions(
            name='trackstatus',
            options={'verbose_name_plural': 'Track statuses'},
        ),
    ]
