# Generated by Django 3.1 on 2021-03-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0079_auto_20210303_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='qr_code',
            field=models.CharField(max_length=200, null=True, verbose_name='QR code '),
        ),
    ]
