# Generated by Django 3.1 on 2021-03-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0080_transaction_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='txid',
        ),
    ]
