# Generated by Django 3.1 on 2021-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0081_auto_20210303_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='response',
            field=models.JSONField(null=True, verbose_name='Response from getting payment'),
        ),
    ]
