# Generated by Django 3.1 on 2021-04-26 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0049_pixapisetting_is_prod'),
        ('core', '0034_auto_20210318_1221'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0082_transaction_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalsurcharge',
            options={'verbose_name': 'Additional surcharge', 'verbose_name_plural': 'Additional surcharges'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='cancellationreason',
            options={'verbose_name': 'Cancellation reason', 'verbose_name_plural': 'Cancellation reasons'},
        ),
        migrations.AlterModelOptions(
            name='cargogroup',
            options={'verbose_name': 'Cargo group', 'verbose_name_plural': 'Cargo groups'},
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'verbose_name': 'Charge', 'verbose_name_plural': 'Charges'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='freightrate',
            options={'verbose_name': 'Freight rate', 'verbose_name_plural': 'Freight rates'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Quote', 'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterModelOptions(
            name='shipmentdetails',
            options={'verbose_name': 'Shipment detail', 'verbose_name_plural': 'Shipment details'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AlterModelOptions(
            name='surcharge',
            options={'verbose_name': 'Surcharge', 'verbose_name_plural': 'Surcharges'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('-date_created',), 'verbose_name': 'Track', 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AlterModelOptions(
            name='trackstatus',
            options={'verbose_name': 'Track status', 'verbose_name_plural': 'Track statuses'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='usagefee',
            options={'verbose_name': 'Usage fee', 'verbose_name_plural': 'Usage fees'},
        ),
        migrations.AlterField(
            model_name='additionalsurcharge',
            name='shipping_mode',
            field=models.ManyToManyField(related_name='additional_surcharges', to='handling.ShippingMode', verbose_name='Shipping mode'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agent_contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Agent contact person'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Client contact person'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_accepted_by_agent',
            field=models.DateTimeField(null=True, verbose_name='Date booking accepted by an agent'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateField(verbose_name='Booking date from'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='freight_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.freightrate', verbose_name='Freight rate'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='release_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handling.releasetype', verbose_name='Release type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shipper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.shipper', verbose_name='Shipper'),
        ),
        migrations.AlterField(
            model_name='cargogroup',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_groups', to='booking.booking', verbose_name='Booking'),
        ),
        migrations.AlterField(
            model_name='cargogroup',
            name='container_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handling.containertype', verbose_name='Container type'),
        ),
        migrations.AlterField(
            model_name='cargogroup',
            name='packaging_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='handling.packagingtype', verbose_name='Packaging type'),
        ),
        migrations.AlterField(
            model_name='cargogroup',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_cargo_groups', to='booking.quote', verbose_name='Quote'),
        ),
        migrations.AlterField(
            model_name='freightrate',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_rates', to='handling.carrier', verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='freightrate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_rates', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='freightrate',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_freight_rates', to='handling.port', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='freightrate',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_freight_rates', to='handling.port', verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='freightrate',
            name='shipping_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_rates', to='handling.shippingmode', verbose_name='Shipping mode'),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='handling.carrier', verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='container_types',
            field=models.ManyToManyField(related_name='surcharges', through='booking.UsageFee', to='handling.ContainerType', verbose_name='Container types'),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.port', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='surcharge',
            name='shipping_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='handling.shippingmode', verbose_name='Shipping mode'),
        ),
        migrations.AlterField(
            model_name='trackstatus',
            name='direction',
            field=models.ManyToManyField(to='booking.Direction', verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='trackstatus',
            name='shipping_mode',
            field=models.ManyToManyField(related_name='tracking_statuses', to='handling.ShippingMode', verbose_name='Shipping mode'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='booking.booking', verbose_name='Booking'),
        ),
    ]
