# Generated by Django 3.1 on 2021-04-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0083_auto_20210318_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_accepted_by_agent',
            field=models.DateTimeField(null=True, verbose_name='Date booking accepted by an agent'),
        ),
    ]
