# Generated by Django 3.1 on 2021-01-25 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websockets', '0002_auto_20210125_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('surcharges', 'Surcharges'), ('freight_rates', 'Freight Rates'), ('requests', 'Requests'), ('operations', 'Operations'), ('operations_import', 'Operations (Imports)'), ('operations_export', 'Operations (Exports)')], max_length=17, verbose_name='Section')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date the notification object created')),
                ('text', models.TextField(verbose_name='Notification text')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Notification is viewed')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='Id of described object')),
                ('users', models.ManyToManyField(related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
