# Generated by Django 3.1 on 2021-01-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0004_auto_20210125_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['date_created']},
        ),
    ]
