# Generated by Django 3.1 on 2021-01-26 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websockets', '0005_auto_20210125_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_viewed',
        ),
        migrations.CreateModel(
            name='NotificationSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is seen by user')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websockets.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='websockets.NotificationSeen', to=settings.AUTH_USER_MODEL),
        ),
    ]
