# Generated by Django 3.1 on 2021-01-26 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websockets', '0007_auto_20210126_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('surcharges', 'Surcharges'), ('freight_rates', 'Freight Rates'), ('requests', 'Requests'), ('operations', 'Operations'), ('operations_import', 'Operations (Imports)'), ('operations_export', 'Operations (Exports)')], max_length=17, verbose_name='Section')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date the notification object created')),
                ('text', models.TextField(verbose_name='Notification text')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='Id of described object')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is seen by user')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websockets.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='websockets.NotificationSeen', to=settings.AUTH_USER_MODEL),
        ),
    ]
