# Generated by Django 3.1 on 2021-01-26 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0008_auto_20210126_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationseen',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_seen', to='websockets.notification'),
        ),
    ]
