# Generated by Django 3.1 on 2021-01-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0009_auto_20210126_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationseen',
            old_name='is_seen',
            new_name='is_viewed',
        ),
    ]
