# Generated by Django 3.1 on 2021-02-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0011_auto_20210129_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_created']},
        ),
    ]
