# Generated by Django 3.1 on 2021-02-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0012_auto_20210201_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_path',
            field=models.CharField(choices=[('booking', 'Booking'), ('billing', 'Billing'), ('operation', 'Operation'), ('surcharge', 'Surcharge'), ('freight_rate', 'Freight Rate')], default='booking', max_length=20, verbose_name='Action path'),
        ),
    ]
