# Generated by Django 3.1 on 2021-02-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0013_notification_action_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
    ]
