# Generated by Django 3.1 on 2021-02-04 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0014_auto_20210202_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='websockets.message'),
        ),
    ]
