# Generated by Django 3.1 on 2021-02-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0015_auto_20210204_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users',
        ),
    ]
