# Generated by Django 3.1 on 2021-02-08 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websockets', '0016_remove_chat_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_perm_to_read', models.BooleanField(default=True, verbose_name='User has permission to read messages')),
                ('has_perm_to_write', models.BooleanField(default=True, verbose_name='User has permission to write messages')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='websockets.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chats', through='websockets.ChatPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
