# Generated by Django 3.1 on 2021-02-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0017_auto_20210208_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatpermission',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='User is online'),
        ),
        migrations.AddField(
            model_name='chatpermission',
            name='unread_messages',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of unread messages'),
        ),
    ]
