# Generated by Django 3.1 on 2021-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0018_auto_20210217_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_path',
            field=models.CharField(choices=[('booking', 'Booking'), ('billing', 'Billing'), ('operation', 'Operation'), ('surcharge', 'Surcharge'), ('freight_rate', 'Freight Rate'), ('support', 'Support')], default='booking', max_length=20, verbose_name='Action path'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='section',
            field=models.CharField(choices=[('surcharges', 'Surcharges'), ('freight_rates', 'Freight Rates'), ('requests', 'Requests'), ('operations', 'Operations'), ('operations_import', 'Operations (Imports)'), ('operations_export', 'Operations (Exports)'), ('chats', 'Chats')], max_length=17, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('operations', 'Operations'), ('requests', 'Requests'), ('billing', 'Billing'), ('rates_and_services', 'Rates and services')], default='requests', max_length=20, verbose_name='Categories'),
        ),
    ]
