# Generated by Django 3.1 on 2021-04-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websockets', '0019_auto_20210318_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-id'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='chatpermission',
            options={'verbose_name': 'Chat permission', 'verbose_name_plural': 'Chat permissions'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_created'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='messagefile',
            options={'verbose_name': 'Message file', 'verbose_name_plural': 'Message files'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_created'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='websockets.chat', verbose_name='Chat'),
        ),
    ]
