# Generated by Django 3.1 on 2020-09-04 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_char_code', models.CharField(max_length=2, null=True, verbose_name='Two char airline code')),
                ('three_char_code', models.CharField(max_length=3, null=True, verbose_name='Three char airline code')),
                ('numeric_code', models.CharField(max_length=3, null=True, verbose_name='Numeric airline code')),
                ('name', models.CharField(max_length=100, verbose_name='Airline title')),
                ('name_additional', models.CharField(max_length=100, null=True, verbose_name='Airline additional title')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='First address line')),
                ('address_additional', models.CharField(max_length=100, null=True, verbose_name='Additional address line')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='Airline city')),
                ('postcode', models.CharField(max_length=20, null=True, verbose_name='Airline postcode')),
                ('cass_controlled', models.BooleanField(default=False, verbose_name='CASS controled')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Carrier title')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('code', models.CharField(max_length=50, verbose_name='Container code')),
                ('description_pt', models.CharField(max_length=100, verbose_name='Description PT')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('mode', models.CharField(max_length=20, null=True, verbose_name='Mode')),
                ('fcl_type', models.CharField(max_length=10, verbose_name='FCL type')),
                ('iata_class', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='IATA class')),
                ('teu', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='TEU')),
                ('height', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Height')),
                ('length', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Width')),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Gross weight')),
                ('tare_weight', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tare weight')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Capacity (M3)')),
                ('iso', models.CharField(max_length=10, null=True, verbose_name='ISO')),
                ('iso_type', models.CharField(max_length=10, null=True, verbose_name='ISO type')),
                ('iso_size', models.CharField(max_length=100, null=True, verbose_name='ISO size')),
                ('iso_description', models.CharField(max_length=150, null=True, verbose_name='ISO description')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Currency three char code')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Fee title')),
                ('fee_type', models.CharField(choices=[('booking', 'Booking Fee'), ('service', 'Service Fee')], max_length=10, verbose_name='Fee type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Fee enabled')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fee value')),
                ('value_type', models.CharField(choices=[('fixed', 'Fixed value'), ('percent', 'Percentage')], max_length=10, verbose_name='Value type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IMOClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='IMO class title')),
                ('imo_class', models.CharField(max_length=50, verbose_name='IMO class')),
            ],
        ),
        migrations.CreateModel(
            name='LocalFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Fee title')),
                ('fee_type', models.CharField(choices=[('booking', 'Booking Fee'), ('service', 'Service Fee')], max_length=10, verbose_name='Fee type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Fee enabled')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Fee value')),
                ('value_type', models.CharField(choices=[('fixed', 'Fixed value'), ('percent', 'Percentage')], max_length=10, verbose_name='Value type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackagingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Packaging code')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('description_pt', models.CharField(max_length=100, verbose_name='Description PT')),
                ('height', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Height')),
                ('length', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Width')),
                ('dimension_unit', models.CharField(max_length=10, verbose_name='Dimension unit')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Weight')),
                ('weight_unit', models.CharField(max_length=10, verbose_name='Weight unit')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Port Code')),
                ('name', models.CharField(max_length=100, verbose_name='Port Name')),
                ('iata', models.CharField(max_length=3, null=True, verbose_name='IATA')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='Port coordinates')),
                ('timezone', models.CharField(max_length=6, verbose_name='Port timezone')),
                ('dst', models.BooleanField(verbose_name='Daylight saving time')),
                ('in_current_country', models.BooleanField(verbose_name='Is in current country')),
                ('in_eu', models.BooleanField(verbose_name='Is in EU')),
                ('economic_group', models.CharField(max_length=100, null=True, verbose_name='Economic group')),
                ('has_airport', models.BooleanField(verbose_name='Has airport?')),
                ('has_border_crossing', models.BooleanField(default=False, verbose_name='Has border crossing?')),
                ('has_customs_lodge', models.BooleanField(default=False, verbose_name='Has customs lodge?')),
                ('discharge', models.BooleanField(default=False, verbose_name='Discharge')),
                ('has_outport', models.BooleanField(default=False, verbose_name='Has outport?')),
                ('has_post', models.BooleanField(default=False, verbose_name='Has post?')),
                ('has_rail', models.BooleanField(default=False, verbose_name='Has rail?')),
                ('has_road', models.BooleanField(verbose_name='Has road?')),
                ('has_seaport', models.BooleanField(verbose_name='Has seaport?')),
                ('has_store', models.BooleanField(default=False, verbose_name='Has store?')),
                ('has_terminal', models.BooleanField(default=False, verbose_name='Has terminal?')),
                ('has_unload', models.BooleanField(default=False, verbose_name='Has unload?')),
                ('name_with_dicriticals', models.CharField(max_length=100, verbose_name='Name with diacriticals')),
                ('is_active', models.BooleanField(default=True, verbose_name='Port is active')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Release type title')),
                ('code', models.CharField(max_length=3, verbose_name='Release code')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Shipping Type Title')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Shipping Mode Title')),
                ('shipping_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_modes', to='handling.shippingtype')),
            ],
        ),
    ]
