# Generated by Django 3.1 on 2020-09-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handling', '0001_initial'),
        ('core', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.state'),
        ),
        migrations.AddField(
            model_name='localfee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.company'),
        ),
        migrations.AddField(
            model_name='localfee',
            name='shipping_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_fees', to='handling.shippingmode'),
        ),
        migrations.AddField(
            model_name='globalfee',
            name='shipping_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_fees', to='handling.shippingmode'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='shipping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='handling.shippingtype'),
        ),
        migrations.AddField(
            model_name='airline',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.state'),
        ),
    ]
