# Generated by Django 3.1 on 2020-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0002_auto_20200904_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalfee',
            name='fee_type',
            field=models.CharField(choices=[('booking', 'Booking Fee'), ('penalty', 'Cancellation Penalty Fee'), ('agent_booking', 'Agent Booking Fee'), ('service', 'Service Fee')], max_length=20, verbose_name='Fee type'),
        ),
        migrations.AlterField(
            model_name='localfee',
            name='fee_type',
            field=models.CharField(choices=[('booking', 'Booking Fee'), ('penalty', 'Cancellation Penalty Fee'), ('agent_booking', 'Agent Booking Fee'), ('service', 'Service Fee')], max_length=20, verbose_name='Fee type'),
        ),
    ]
