# Generated by Django 3.1 on 2020-09-16 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0003_auto_20200915_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containertype',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_types', to='handling.shippingtype'),
        ),
    ]
