# Generated by Django 3.1 on 2020-09-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0006_auto_20200928_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalfee',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Fee enabled'),
        ),
        migrations.AlterField(
            model_name='localfee',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Fee enabled'),
        ),
    ]
