# Generated by Django 3.1 on 2020-09-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0007_auto_20200928_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalfee',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fee value'),
        ),
        migrations.AlterField(
            model_name='globalfee',
            name='value_type',
            field=models.CharField(choices=[('fixed', 'Fixed value'), ('percent', 'Percentage')], default='fixed', max_length=10, verbose_name='Value type'),
        ),
        migrations.AlterField(
            model_name='localfee',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Fee value'),
        ),
        migrations.AlterField(
            model_name='localfee',
            name='value_type',
            field=models.CharField(choices=[('fixed', 'Fixed value'), ('percent', 'Percentage')], default='fixed', max_length=10, verbose_name='Value type'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='description_pt',
            field=models.CharField(max_length=100, null=True, verbose_name='Description PT'),
        ),
    ]
