# Generated by Django 3.1 on 2020-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0008_auto_20200929_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingtype',
            name='dimension_unit',
            field=models.CharField(max_length=10, null=True, verbose_name='Dimension unit'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='weight_unit',
            field=models.CharField(max_length=10, null=True, verbose_name='Weight unit'),
        ),
    ]
