# Generated by Django 3.1 on 2020-09-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0009_auto_20200929_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='name_with_dicriticals',
            new_name='name_with_diacriticals',
        ),
    ]
