# Generated by Django 3.1 on 2020-10-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0010_auto_20200930_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ('code',)},
        ),
    ]
