# Generated by Django 3.1 on 2020-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0011_auto_20201013_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='is_dangerous',
            field=models.BooleanField(default=False, verbose_name='Is dangerous'),
        ),
        migrations.AddField(
            model_name='containertype',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Is frozen'),
        ),
        migrations.AddField(
            model_name='packagingtype',
            name='shipping_modes',
            field=models.ManyToManyField(related_name='packaging_types', to='handling.ShippingMode'),
        ),
        migrations.AddField(
            model_name='shippingmode',
            name='is_need_volume',
            field=models.BooleanField(default=False, verbose_name='Is need volume'),
        ),
    ]
