# Generated by Django 3.1 on 2020-11-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0012_auto_20201102_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containertype',
            name='is_dangerous',
        ),
        migrations.AddField(
            model_name='containertype',
            name='can_be_dangerous',
            field=models.BooleanField(default=False, verbose_name='Can be dangerous'),
        ),
    ]
