# Generated by Django 3.1 on 2020-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0013_auto_20201103_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active in the platform'),
        ),
        migrations.AddField(
            model_name='currency',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main currency in the platform'),
        ),
    ]
