# Generated by Django 3.1 on 2020-11-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0014_auto_20201105_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmode',
            name='has_freight_containers',
            field=models.BooleanField(default=False, verbose_name='Has container types in freight rate'),
        ),
        migrations.AddField(
            model_name='shippingmode',
            name='has_surcharge_containers',
            field=models.BooleanField(default=False, verbose_name='Has container types in surcharge'),
        ),
    ]
