# Generated by Django 3.1 on 2020-11-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0015_auto_20201105_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Exchange rate')),
                ('spread', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Spread')),
                ('currency', models.ForeignKey(limit_choices_to=models.Q(('is_active', True), ('is_main', False)), on_delete=django.db.models.deletion.CASCADE, to='handling.currency')),
            ],
        ),
    ]
