# Generated by Django 3.1 on 2020-11-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0018_clientquotesetting_clientsearchsetting_generalsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientQuoteSetting',
        ),
        migrations.DeleteModel(
            name='ClientSearchSetting',
        ),
        migrations.DeleteModel(
            name='GeneralSetting',
        ),
    ]
