# Generated by Django 3.1 on 2020-11-13 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0019_auto_20201113_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPlatformSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_results', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of rates results will return')),
                ('show_carrier_name', models.BooleanField(default=False, verbose_name='Hide/show carrier name in search results')),
                ('number_of_bids', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of bids client can receive')),
                ('number_of_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of days a quote will be shown to ff')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_freight_forwarder_name', models.CharField(default='after_booking', max_length=50, verbose_name='Hide/show freight forwarder')),
                ('number_of_days_request_can_stay', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of days request can stay in client list until discarded')),
                ('export_deadline_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of days that the agent will have to confirm a booking request')),
                ('import_deadline_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of days that the agent will have to confirm a booking request')),
            ],
        ),
    ]
