# Generated by Django 3.1 on 2020-11-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0020_clientplatformsetting_generalsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientplatformsetting',
            old_name='show_carrier_name',
            new_name='hide_carrier_name',
        ),
    ]
