# Generated by Django 3.1 on 2020-12-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0022_auto_20201202_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientplatformsetting',
            name='enable_booking_fee_payment',
            field=models.BooleanField(default=True, verbose_name='Enable booking/service fee payment to book freight rate'),
        ),
    ]
