# Generated by Django 3.1 on 2020-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0023_clientplatformsetting_enable_booking_fee_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientplatformsetting',
            name='hide_carrier_name',
            field=models.BooleanField(default=False, verbose_name='Hide carrier name in search results'),
        ),
    ]
