# Generated by Django 3.1 on 2020-12-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0025_auto_20201216_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsetting',
            name='air_tracking_api_url',
            field=models.CharField(max_length=256, null=True, verbose_name='Api url to track delivery progress of air shipment'),
        ),
    ]
