# Generated by Django 3.1 on 2020-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0026_generalsetting_air_tracking_api_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirTrackingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='Api url to track delivery progress of air shipment')),
                ('username', models.CharField(max_length=30, verbose_name='Username credential')),
                ('password', models.CharField(max_length=30, verbose_name='Password credential')),
                ('pima', models.CharField(max_length=20, verbose_name='PIMA')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='air_tracking_api_url',
        ),
    ]
