# Generated by Django 3.1 on 2020-12-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0027_auto_20201217_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AirTrackingSettings',
            new_name='AirTrackingSetting',
        ),
    ]
