# Generated by Django 3.1 on 2020-12-23 11:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handling', '0030_carrier_scac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date the notification created')),
                ('section', models.CharField(choices=[('requests', 'Requests'), ('operations', 'Operations'), ('rates', 'Rates'), ('surcharges', 'Surcharges')], max_length=20, verbose_name='Section of the notification')),
                ('text', models.TextField(verbose_name='Notification text')),
            ],
        ),
        migrations.CreateModel(
            name='SeaTrackingSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='Api url to track delivery progress of sea shipment')),
                ('api_key', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Invalid format. Must be: 0000-0000-0000-0000', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{4}$')], verbose_name='PIMA')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is seen by user')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handling.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ManyToManyField(related_name='notifications', through='handling.NotificationSeen', to=settings.AUTH_USER_MODEL),
        ),
    ]
