# Generated by Django 3.1 on 2020-12-23 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0031_auto_20201223_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatrackingsetting',
            name='api_key',
            field=models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Invalid format. Must be: 0000-0000-0000-0000', regex='^\\d{4}-\\d{4}-\\d{4}-\\d{4}$')], verbose_name='Api key'),
        ),
    ]
