# Generated by Django 3.1 on 2020-12-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0035_auto_20201223_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='code',
            field=models.CharField(max_length=2, null=True, verbose_name='2 letter air code'),
        ),
    ]
