# Generated by Django 3.1 on 2020-12-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0036_carrier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='prefix',
            field=models.CharField(max_length=3, null=True, verbose_name='Airline prefix'),
        ),
    ]
