# Generated by Django 3.1 on 2020-12-29 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20201202_1321'),
        ('handling', '0037_carrier_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixApiSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=256, verbose_name='Pix api base url')),
                ('token_uri', models.CharField(max_length=256, verbose_name='Pix api token uri')),
                ('cob_uri', models.CharField(max_length=256, verbose_name='Pix api cob uri')),
                ('client_id', models.TextField(verbose_name='Client id')),
                ('client_secret', models.TextField(verbose_name='Client secret')),
                ('developer_key', models.TextField(verbose_name='Developer key')),
                ('basic_token', models.TextField(verbose_name='Basic token value')),
                ('bank_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_api', to='core.bankaccount')),
            ],
        ),
    ]
