# Generated by Django 3.1 on 2021-01-12 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0040_auto_20210104_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='number_of_days_request_can_stay',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of days an unpaid booking request can stay in client list until discarded'),
        ),
    ]
