# Generated by Django 3.1 on 2021-01-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0041_auto_20210112_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingexchangerate',
            options={'ordering': ['-date']},
        ),
    ]
