# Generated by Django 3.1 on 2021-01-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0043_auto_20210125_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationseen',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationseen',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationSeen',
        ),
    ]
