# Generated by Django 3.1 on 2021-02-01 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20201109_1205'),
        ('handling', '0044_auto_20210126_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='state',
        ),
        migrations.RemoveField(
            model_name='port',
            name='discharge',
        ),
        migrations.RemoveField(
            model_name='port',
            name='economic_group',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_airport',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_border_crossing',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_customs_lodge',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_outport',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_post',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_rail',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_road',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_seaport',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_store',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_terminal',
        ),
        migrations.RemoveField(
            model_name='port',
            name='has_unload',
        ),
        migrations.RemoveField(
            model_name='port',
            name='in_current_country',
        ),
        migrations.RemoveField(
            model_name='port',
            name='in_eu',
        ),
        migrations.RemoveField(
            model_name='port',
            name='name_with_diacriticals',
        ),
        migrations.RemoveField(
            model_name='port',
            name='state',
        ),
        migrations.AddField(
            model_name='port',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.country'),
        ),
        migrations.AlterField(
            model_name='port',
            name='dst',
            field=models.BooleanField(default=False, verbose_name='Daylight saving time'),
        ),
        migrations.AlterField(
            model_name='port',
            name='timezone',
            field=models.CharField(max_length=6, null=True, verbose_name='Port timezone'),
        ),
    ]
