# Generated by Django 3.1 on 2021-02-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0045_auto_20210201_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='dst',
        ),
    ]
