# Generated by Django 3.1 on 2021-02-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0046_remove_port_dst'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='port_or_airport',
            field=models.CharField(choices=[('port', 'Port'), ('airport', 'Airport')], default='port', max_length=10, verbose_name='Port or airport'),
        ),
    ]
