# Generated by Django 3.1 on 2021-03-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0047_port_port_or_airport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Сurrencies'},
        ),
        migrations.RenameField(
            model_name='pixapisetting',
            old_name='cob_uri',
            new_name='qr_cob_uri',
        ),
    ]
