# Generated by Django 3.1 on 2021-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0048_auto_20210303_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixapisetting',
            name='is_prod',
            field=models.BooleanField(default=False, verbose_name='Production environment is active'),
        ),
    ]
