# Generated by Django 3.1 on 2021-05-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210515_0840'),
        ('location', '0005_auto_20210303_0915'),
        ('handling', '0049_pixapisetting_is_prod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airline',
            options={'verbose_name': 'Airline', 'verbose_name_plural': 'Airlines'},
        ),
        migrations.AlterModelOptions(
            name='airtrackingsetting',
            options={'verbose_name': 'Air tracking setting', 'verbose_name_plural': 'Air tracking settings'},
        ),
        migrations.AlterModelOptions(
            name='billingexchangerate',
            options={'ordering': ['date'], 'verbose_name': 'Billing exchange rate', 'verbose_name_plural': 'Billing exchange rates'},
        ),
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'Carrier', 'verbose_name_plural': 'Carriers'},
        ),
        migrations.AlterModelOptions(
            name='clientplatformsetting',
            options={'verbose_name': 'Client platform setting', 'verbose_name_plural': 'Client platform settings'},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'verbose_name': 'Container type', 'verbose_name_plural': 'Container types'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Exchange rate', 'verbose_name_plural': 'Exchange rates'},
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'General setting', 'verbose_name_plural': 'General settings'},
        ),
        migrations.AlterModelOptions(
            name='globalfee',
            options={'verbose_name': 'Global fee', 'verbose_name_plural': 'Global fees'},
        ),
        migrations.AlterModelOptions(
            name='imoclass',
            options={'verbose_name': 'Imo class', 'verbose_name_plural': 'Imo classes'},
        ),
        migrations.AlterModelOptions(
            name='localfee',
            options={'verbose_name': 'Company Specific Fee', 'verbose_name_plural': 'Company Specific Fees'},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'verbose_name': 'Packaging type', 'verbose_name_plural': 'Packaging types'},
        ),
        migrations.AlterModelOptions(
            name='pixapisetting',
            options={'verbose_name': 'Pix api setting', 'verbose_name_plural': 'Pix api settings'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ('code',), 'verbose_name': 'Port', 'verbose_name_plural': 'Ports'},
        ),
        migrations.AlterModelOptions(
            name='releasetype',
            options={'verbose_name': 'Release type', 'verbose_name_plural': 'Release types'},
        ),
        migrations.AlterModelOptions(
            name='seatrackingsetting',
            options={'verbose_name': 'Sea tracking setting', 'verbose_name_plural': 'Sea tracking settings'},
        ),
        migrations.AlterModelOptions(
            name='shippingmode',
            options={'verbose_name': 'Shipping mode', 'verbose_name_plural': 'Shipping modes'},
        ),
        migrations.AlterModelOptions(
            name='shippingtype',
            options={'verbose_name': 'Shipping type', 'verbose_name_plural': 'Shipping types'},
        ),
        migrations.AddField(
            model_name='port',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='port',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='shipping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='handling.shippingtype', verbose_name='Shipping type'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Carrier name'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='shipping_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_types', to='handling.shippingmode', verbose_name='Shipping mode'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_active', True), ('is_main', False)), on_delete=django.db.models.deletion.CASCADE, to='handling.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='globalfee',
            name='shipping_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_fees', to='handling.shippingmode', verbose_name='Global fee'),
        ),
        migrations.AlterField(
            model_name='localfee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='localfee',
            name='shipping_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_fees', to='handling.shippingmode', verbose_name='Shipping mode'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='shipping_modes',
            field=models.ManyToManyField(related_name='packaging_types', to='handling.ShippingMode', verbose_name='Shipping modes'),
        ),
        migrations.AlterField(
            model_name='port',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='port',
            name='iata',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='IATA'),
        ),
        migrations.AlterField(
            model_name='port',
            name='timezone',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Port timezone'),
        ),
        migrations.AlterField(
            model_name='shippingmode',
            name='has_freight_containers',
            field=models.BooleanField(default=False, verbose_name='Requires containers for rate registration'),
        ),
        migrations.AlterField(
            model_name='shippingmode',
            name='has_surcharge_containers',
            field=models.BooleanField(default=False, verbose_name='Requires container for surcharges'),
        ),
        migrations.AlterField(
            model_name='shippingmode',
            name='shipping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_modes', to='handling.shippingtype', verbose_name='Shipping type'),
        ),
    ]
