# Generated by Django 3.1 on 2020-09-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, verbose_name='Country Code')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Currency is active')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='handling.currency')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='Zone Code')),
                ('name', models.CharField(max_length=100, verbose_name='Zone Name')),
                ('zone_type', models.CharField(choices=[('TAX', 'TAX'), ('RAT', 'RAT'), ('RPT', 'RPT')], max_length=3, verbose_name='Zone type')),
                ('carrier_or_customer', models.CharField(max_length=50, null=True, verbose_name='Carrier or customer')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='State Name')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='State Code')),
                ('name', models.CharField(max_length=100, verbose_name='State Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Currency is active')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.country')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.region')),
            ],
        ),
    ]
