# Generated by Django 3.1 on 2020-11-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20201105_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='chosen_for_platform',
            new_name='is_main',
        ),
    ]
