# Generated by Django 3.1 on 2021-02-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handling', '0045_auto_20210201_1008'),
        ('location', '0003_auto_20201109_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InternationalZone',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveField(
            model_name='state',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
