# Generated by Django 3.1 on 2021-03-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20210201_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
