# Generated by Django 3.2.5 on 2021-07-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_auto_20210426_1640'),
        ('location', '0006_auto_20210515_0840'),
    ]

    operations = [
    ]
