# Generated by Django 3.1 on 2020-09-08 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuptoken',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signuptoken',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='master_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Master email address'),
        ),
        migrations.AlterField(
            model_name='signuptoken',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
