# Generated by Django 3.1 on 2020-09-08 12:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200908_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, null=True, region=None, verbose_name='Phone number'),
        ),
    ]
