# Generated by Django 3.1 on 2020-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_company_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuprequest',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
