# Generated by Django 3.1 on 2020-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_signuprequest_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Is default bank account or not'),
        ),
    ]
