# Generated by Django 3.1 on 2020-09-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bankaccount_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
