# Generated by Django 3.1 on 2020-09-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bankaccount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='asdads'),
        ),
    ]
