# Generated by Django 3.1 on 2020-09-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200921_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='good',
            field=models.DateField(null=True, verbose_name='asdasd'),
        ),
    ]
