# Generated by Django 3.1 on 2020-09-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200921_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='default',
            new_name='is_default',
        ),
    ]
