# Generated by Django 3.1 on 2020-09-23 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200921_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format. Must be: 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}-\\d{2}$')], verbose_name='Tax id Number'),
        ),
    ]
