# Generated by Django 3.1 on 2020-09-24 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200924_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid format. Must contains only numbers', regex='^\\d+$')], verbose_name='Account Number'),
        ),
    ]
