# Generated by Django 3.1 on 2020-10-02 07:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200925_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='first_name',
            field=models.CharField(max_length=150, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='last_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='master_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=13, null=True, region=None, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='position',
            field=models.CharField(max_length=100, null=True, verbose_name='Position in company'),
        ),
    ]
