# Generated by Django 3.1 on 2020-10-02 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20201002_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format. Must contains only numbers', regex='^\\d+$')], verbose_name='Account Number'),
        ),
    ]
