# Generated by Django 3.1 on 2020-10-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201002_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, help_text='User profile photo.', max_length=255, null=True, upload_to='profile_pics', verbose_name='Profile Photo'),
        ),
    ]
