# Generated by Django 3.1 on 2020-10-27 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201027_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='zip_code',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid format. Must contains only letters, numbers or character [-].', regex='^[a-zA-Z0-9]+[-]?[a-zA-Z0-9]+$')], verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='signuprequest',
            name='zip_code',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid format. Must contains only letters, numbers or character [-].', regex='^[a-zA-Z0-9]+[-]?[a-zA-Z0-9]+$')], verbose_name='Zip Code'),
        ),
    ]
