# Generated by Django 3.1 on 2020-11-04 17:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201102_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('address_line_first', models.CharField(max_length=100, null=True, verbose_name='First address line')),
                ('address_line_second', models.CharField(blank=True, max_length=100, null=True, verbose_name='Second address line')),
                ('state', models.CharField(max_length=100, null=True, verbose_name='State')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Invalid format. Must contains only letters, numbers or one hyphen. A zip code cannot begin or end with a hyphen.', regex='^[a-zA-Z0-9]+[-]?[a-zA-Z0-9]+$')], verbose_name='Zip Code')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Shippers contact name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None, verbose_name='Phone number')),
                ('phone_additional', phonenumber_field.modelfields.PhoneNumberField(max_length=13, null=True, region=None, verbose_name='Additional phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
    ]
