# Generated by Django 3.1 on 2020-11-25 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_number',
            field=models.CharField(default=000, max_length=3, validators=[django.core.validators.RegexValidator(message='Invalid format. Must contains only numbers', regex='^\\d{3}$')], verbose_name='Bank Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format. Must contains only numbers', regex='^\\d+$')], verbose_name='Account Number'),
        ),
    ]
