# Generated by Django 3.1 on 2020-11-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201125_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='pix_key',
            field=models.CharField(max_length=77, null=True, verbose_name='Pix payment key'),
        ),
    ]
