# Generated by Django 3.1 on 2020-12-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bankaccount_pix_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_platforms',
            field=models.BooleanField(default=False, verbose_name='Is bank account of the platform'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.company'),
        ),
    ]
