# Generated by Django 3.1 on 2020-12-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201202_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking')], default='savings', max_length=10, verbose_name='Account Type'),
        ),
    ]
