# Generated by Django 3.1 on 2021-01-06 19:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0067_auto_20210106_1943'),
        ('core', '0027_auto_20201202_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Company rating from 1 to 10')),
                ('comment', models.TextField(verbose_name='Review text')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved by platform')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date review created')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reviewer__companies', '-date_created'],
            },
        ),
    ]
