# Generated by Django 3.1 on 2021-01-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['reviewer__companies__name', '-date_created']},
        ),
    ]
