# Generated by Django 3.1 on 2021-01-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210106_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='booking',
            new_name='operation',
        ),
    ]
