# Generated by Django 3.1 on 2021-01-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_company_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='Is company partner'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email address'),
        ),
    ]
