# Generated by Django 3.1 on 2021-01-26 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210112_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea_import_shipment_arrival_alert', models.BooleanField(default=False, verbose_name='Sea import shipment alerts')),
                ('sea_import_shipment_arrival_alert_days', models.PositiveIntegerField(default=0, verbose_name='Sea import shipment alerts in days')),
                ('import_shipment_departure_alert', models.BooleanField(default=False, verbose_name='Import shipment departure alerts')),
                ('export_shipment_arrival_alert', models.BooleanField(default=False, verbose_name='Export shipment arrival alerts')),
                ('operation_details_change', models.BooleanField(default=False, verbose_name='Operation details change')),
                ('surcharge_expiration', models.BooleanField(default=False, verbose_name='Surcharge expiration')),
                ('surcharge_expiration_days', models.PositiveIntegerField(default=0, verbose_name='Surcharge expiration in days')),
                ('freight_rate_expiration', models.BooleanField(default=False, verbose_name='Freight rate expiration')),
                ('freight_rate_expiration_days', models.PositiveIntegerField(default=0, verbose_name='Freight rate expiration in days')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
