# Generated by Django 3.1 on 2021-03-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0082_transaction_response'),
        ('core', '0033_emailnotificationsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disable functionality'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='operation',
            field=models.OneToOneField(limit_choices_to=models.Q(status__in=('confirmed', 'canceled_by_client', 'canceled_by_agent', 'canceled_by_system')), on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
    ]
