# Generated by Django 3.1 on 2021-03-03 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_emailnotificationsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
