# Generated by Django 3.2.5 on 2021-07-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210318_0939'),
        ('core', '0034_auto_20210515_0840'),
        ('core', '0035_auto_20210426_1640'),
    ]

    operations = [
    ]
